import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { site } from "@/config/site";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 300 600 800 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 300 600 800 900",
});
const bricolageGrotesque = localFont({
    src: "./fonts/BricolageGrotesque_24pt-Bold.ttf",
    variable: "--font-grotesque-bold",
    weight: "100 300 600 800 900",
});

export const metadata: Metadata = {
    title: {
        default: site.title,
        template: `%s | ${site.title}`,
    },
    metadataBase: new URL(`${site.baseUrl}`),
    description: "Generated by create next app",
    keywords: [
        "Next.js",
        "React",
        "Tailwind CSS",
        "Server Components",
        "Radix UI",
    ],
    authors: [{ name: site.author }],
    creator: site.author,
    publisher: site.author,
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${bricolageGrotesque.variable} antialiased container max-w-screen-lg m-4 mx-auto`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
