import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { ScrollProgress } from "@/components/magicui/scroll-progress";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Indie_Flower, Poppins } from "next/font/google";
import "./globals.css";
import FooterSection from "@/components/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const indieFlower = Indie_Flower({
    variable: "--font-indie-flower",
    weight: "400",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${indieFlower.variable} ${poppins.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <ScrollProgress />
                    {children}
                    <FooterSection />
                </ThemeProvider>
            </body>
        </html>
    );
}
